version: '3'

services:
  nginx:
    image: 'nginx:latest'
    working_dir: /var/www/localhost
    ports:
      - '80:80'
    volumes:
      - './nginx/conf.d:/etc/nginx/conf.d'
      - './../src:/var/www/localhost'
    links:
      - php
  php:
    build: 'php'
    working_dir: /var/www/localhost
    volumes:
      - './php/php.ini:/usr/local/etc/php/conf.d/php-override.ini'
      - './../src:/var/www/localhost'
  node:
    build: 'node'
    working_dir: /var/www/localhost
    volumes:
      - './../src:/var/www/localhost'
